### ISSUE TITLE
Type 'T' does not satisfy the constraint 'TypedDocumentData<T>

### ISSUE THREAD

**Issue by arjunyel** [bbangert/typesafe-node-firestore#1]
Hello, thank you for the awesome library :D I actually started my own version tonight but then came across yours!

I am making a wrapper function over my calls that constrains what document interfaces are available, basically making a compile time schema check

```
import * as admin from 'firebase-admin';
import { TypedCollectionReference, TypedQuery } from 'typesafe-node-firestore';

interface Author {
  penName: string;
  shortBiography: string;
  posts: string[];
}

interface Comment {
  id: string;
  text: string;
}

export type IDatabaseSchema = Author | Comment;

export const getDocsFromCollection = async <T extends IDatabaseSchema>(collection: string) => {
  const collectionRef = admin
    .firestore()
    .collection(collection) as TypedCollectionReference<T>;

  let whereQuery: TypedQuery<T>;
};
```

The error is on the last line

```
Type 'T' does not satisfy the constraint 'TypedDocumentData<T>'.
  Type 'IDatabaseSchema' is not assignable to type 'TypedDocumentData<T>'.
    Type 'Author' is not assignable to type 'TypedDocumentData<T>'.
      Index signature is missing in type 'Author'.
```

It seems that a type alias can't be used, it will only work for an interface? Is there a way to constrain it to certain interfaces? Thank you for help!

**Comment by bbangert** [comment]
So, a caveat first, I am a beginner in TypeScript. Someone that knows more may have a better answer, but based on the error *I think* the problem is that you're not extending the right type. The `T` used here must extend firestores DocumentData. I played with your example and made the error go away by changing your `getDocsFromCollection` like so:
```typescript
import * as firestore from '@google-cloud/firestore'
export const getDocsFromCollection = async <T extends IDatabaseSchema & firestore.DocumentData>(collection: string) => {
```

This is because the `T` used in `TypedDocumentData` extends `firestore.DocumentData`.

**Comment by arjunyel** [comment]
Yesss that worked perfectly, thank you for the help!
